config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions" }

  devise_scope :user do
    authenticated :user do
      root to: 'static_pages#home', as: :authenticated_root
    end
    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :albums do 
    resources :photos, shallow: true do
      member do
        get "serve"
      end
    end
  end

  get "/photos" => "photos#all_photos"

  get "/user/photos" => "photos#user_photos"

  get "/error" => "static_pages#error"

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  
  validates :name, presence: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user

  def index
    @albums = @user.albums
  end

  def new
    @album = @user.albums.new
  end

  def create
    @album = @user.albums.new(album_params)
    
    if @album.save
      flash[:notice] = "album created"
      redirect_to @album
    else
      render 'new'
    end
  end

  def show
    @album = @user.albums.find(params[:id])
  end

  def edit
    @album = @user.albums.find(params[:id])
  end

  def update
    @album = @user.albums.find(params[:id])
      if @album.update_attributes(album_params)
        redirect_to @album
      else
        render 'edit'        
      end 
    end
  end

  def destroy
    @album = @user.albums.find(params[:id])
    @album.destroy
    if @album.delete
      redirect_to albums_path
    end
  end

  private
    def album_params
       params.require(:album).permit(:name, :description)
    end

    def check_user
      unless @user = current_user
        redirect_to authenticated_root_path
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/edit.html.slim
.content class="background panel panel-primary"
  p class="notice" = notice
    = alert
  h3 Edit album 
  .panel-body
    = form_for @album do |a|
      .form = a.text_field :name, class: "field", placeholder: "Album name"
      .form = a.text_area :description, class: "field", placeholder: "Description"
      .form = a.submit "Update", method: :update, class: "btn btn-primary"
      .form = link_to "Cancel", :back, class: "btn btn-warning"

app/views/albums/index.html.slim
.content class="background panel panel-primary"
  p class="notice" = notice 
    = alert
  = link_to "New album", new_album_path, class: "btn btn-primary margin-left-15"
  .panel-body
    - @albums.each do |a|
      .col-md-3 class="col-sm-4 col-xs-12 album"
        h3 = link_to a.name, album_photos_path(a)
        p = a.description
        = link_to "Info", album_path(a), class: "btn btn-info"
        = link_to "Edit ", edit_album_path(a), class: "btn btn-success"
        = link_to "Remove", @album, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"

app/views/albums/new.html.slim
.content class="background panel-primary panel"
  p class="notice" = notice
    = alert
  h3.centered New album
  .panel-body  
    = form_for @album do |a|
      .form = a.text_field :name, class: "field", placeholder: "Album name"
      .form = a.text_area :description, class: "field", placeholder: "Description", size: "60x10"
      .form = a.submit "Create", method: :create, class: "btn btn-primary"
    = link_to "Cancel", :back, class: "btn btn-warning"

app/views/albums/show.html.slim
.content class="background panel panel-primary"
  p class="notice" = notice 
    = alert
  
  h3 = @album.name
  p User id: 
  = @album.user_id
  p Description: 
  = @album.description
  p Created at:
  = @album.created_at
  br
  = link_to "Edit ", edit_album_path(@album), class: "btn btn-success"
  = link_to "Remove", @album, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"
  = link_to "Back", :back, class: "btn btn-warning"