config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions" }

  devise_scope :user do
    authenticated :user do
      root to: 'static_pages#home', as: :authenticated_root
    end
    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :albums do 
    resources :photos, shallow: true do
      member do
        get "serve"
      end
    end
  end

  get "/photos" => "photos#all_photos"

  get "/user/photos" => "photos#user_photos"

  get "/error" => "static_pages#error"

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :album
	has_and_belongs_to_many :tags

	validates :name, presence: true
	validates :data, presence: true

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!
  before_filter :select_album, except: [:all_photos, :user_photos, :show, :serve, :destroy, :edit, :update]

  def index
    @album = current_user.albums.find(params[:album_id])
    @photos = @album.photos
  end

  def new
    @photo = @album.photos.new
  end

  def create
    @photo = @album.photos.new(photo_params) do |t|
      if photo_params[:data]
        t.data = photo_params[:data].read
        t.filename = photo_params[:data].original_filename
        t.content_type = photo_params[:data].content_type
      end
      if t.name == ""
        t.name = t.filename
      else
        t.name = t.name + '.' + t.content_type[6,6]
      end
      t.user_id = current_user.id
    end
    if @photo.save
      redirect_to album_photos_path
    else
      redirect_to :back
      flash.now[:notice] = "fill in all filds"
    end
  end

  def show
    @album = Album.find(Photo.find(params[:id]).album_id)
    if @album.user_id == current_user.id
      @photo = @album.photos.find(params[:id])
    else
      redirect_to :error
    end
  end

  def serve
    @photo = Photo.find(params[:id])
    send_data @photo.data, filename: "#{@photo.filename}.jpg", disposition: "inline"
  end

  def edit
    @album = Album.find(Photo.find(params[:id]).album_id)
    if @album.user_id == current_user.id
      @photo = @album.photos.find(params[:id])
    else
      redirect_to :error
    end
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update(photo_params)
      redirect_to photo_path
    else
      redirect_to 'show'
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    if @photo.delete
      redirect_to :back
    end
  end

  def all_photos
    @photos = Photo.all

  end

  def user_photos
    @user = current_user
    @photos = @user.photos.all
  end

  private
    def photo_params
      params.require(:photo).permit(:name, :user_id, :album_id, :filename, :content_type, :data)
    end

    def select_album
      @album = Album.find(params[:album_id])
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/all_photos.html.slim
.content class="background panel panel-primary"
  p class="notice" = notice 
    = alert
  h3 All photos
  .row
    - @photos.each do |p|
      .col-md-3 class="col-sm-4 col-xs-6 height200"

        = image_tag url_for(controller: 'photos', action: 'serve', id: p.id) , class: "index-image", id: "#{p.id}", "data-toggle"=>'modal', "data-target:"=>"#myModal", type: "button", 'data-photoid'=>"#{p.id}", 'data-name'=>"#{p.name.capitalize}"
        br
        p.name-field class="centered" = p.name.capitalize

    <div class="modal fade bs-example-modal-lg" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
            <div class="modal-dialog modal-lg" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="myModalLabel">
                  </h4>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
                  <button type="button" class="btn btn-primary">Save changes</button>
                </div>
              </div>
            </div>
    </div>

app/views/photos/edit.html.slim
.content class="background panel panel-primary"
  p class="notice" = notice 
    = alert
  h3 New Photo
  = form_for @photo do |f|
    = f.text_field :name, class: "field", placeholder: "Photo name"
    br
    = f.file_field :data, class: "field"
    br
    = f.submit "Update", class: "btn btn-primary"

app/views/photos/index.html.slim
.content class="background panel panel-primary"
  p class="notice" = notice 
    = alert
  = link_to "New photo", new_album_photo_path(@album), class: "btn btn-primary"
  h3 = @album.name
  
  .row
    - @photos.each do |p|
      .col-md-3 class="col-sm-4 col-xs-6 height200"

        = image_tag url_for(controller: 'photos', action: 'serve', id: p.id) , class: "index-image", id: "#{p.id}", "data-toggle"=>'modal', "data-target:"=>"#myModal", type: "button", 'data-photoid'=>"#{p.id}", 'data-name'=>"#{p.name.capitalize}"

        p.name-field class="centered" = p.name.capitalize

        .margin-top-bot-5
          = link_to "Open", photo_path(p), class: "btn btn-success"
          = link_to "Delete", p, method: :delete, class: "btn btn-danger"

    <div class="modal fade bs-example-modal-lg" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
            <div class="modal-dialog modal-lg" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="myModalLabel">
                  </h4>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
                  <button type="button" class="btn btn-primary">Save changes</button>
                </div>
              </div>
            </div>
    </div>

app/views/photos/new.html.slim
.content class="background panel panel-primary"
  p class="notice" = notice 
    = alert
  h3 New Photo
  = form_for :photo, as: @photo, url: { action: 'create' }, html: { multipart: true } do |f|
  
    = f.text_field :name, class: "field", placeholder: "Photo name"
    br
    = f.file_field :data, class: "field"
    = f.submit "Add photo", class: "btn btn-primary photo-btn", content: "3"

app/views/photos/show.html.slim
.content class="background panel panel-primary"
  p class="notice" = notice 
    = alert
  <h4>
    <span class="label label-default">
      = @photo.name.capitalize
    </span>
  </h4>
  .row
    = image_tag serve_photo_path(@photo), class: "show-image col-xs-12 col-md-12"
    .margin-left-15 
      = link_to "Change", edit_photo_path(@photo), class: "btn btn-success"
      = link_to "Delete", @photo, controller: :photos, action: :delete, method: :delete, class: "btn btn-danger"

app/views/photos/user_photos.html.slim
.content class="background panel panel-primary"
  p class="notice" = notice 
    = alert
  h3 My photos
  .row
    - @photos.each do |p|
      .col-md-3 class="col-sm-4 col-xs-6 height200"
        = image_tag url_for(controller: 'photos', action: 'serve', id: p.id) , class: "index-image", id: "#{p.id}", "data-toggle"=>'modal', "data-target:"=>"#myModal", type: "button", 'data-photoid'=>"#{p.id}", 'data-name'=>"#{p.name.capitalize}"
        p.name-field = p.name.capitalize
        = link_to "Open", photo_path(p), class: "btn btn-success"
        = link_to "Delete", p, method: :delete, class: "btn btn-danger"

    <div class="modal fade bs-example-modal-lg" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
            <div class="modal-dialog modal-lg" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="myModalLabel">
                  </h4>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
                  <button type="button" class="btn btn-primary">Add comment</button>
                </div>
              </div>
            </div>
    </div>