config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions" }

  devise_scope :user do
    authenticated :user do
      root to: 'static_pages#home', as: :authenticated_root
    end
    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :albums do 
    resources :photos, shallow: true do
      member do
        get "serve"
      end
    end
  end

  get "/photos" => "photos#all_photos"

  get "/user/photos" => "photos#user_photos"

  get "/error" => "static_pages#error"

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_nav.html.slim
.navbar-vertical
    nav class="navbar navbar-inverse navbar-fixed-left"
      p.centered Logged in as:
      .nav
        ul class="nav nav-pills nav-stacked list-group"
          h4.margin-left-15
            <span class="label label-default">
              = current_user.email
            </span>
          li role="presentation" = link_to "Home", authenticated_root_path, class: "nav-hover"
          li role="presentation" = link_to "My albums", albums_path, class: "nav-hover"
          li role="presentation" = link_to "My photos", user_photos_path, class: "nav-hover"
          li role="presentation" = link_to "Find photos", photos_path, class: "nav-hover"
      .nav-offset
      .margin-left-15
        br
        h5 Its personal Photo album
        p Email:
        a href="#" Naytlender@gmail.com
        br
        h5 c. All rights reserved by localhost:3000
      .btn-hide
        <span class="span glyphicon glyphicon-menu-left vertical-centered centered" aria-hidden="true"></span>

app/views/layouts/_navbar.html.slim
nav class="navbar navbar-inverse nav-fixed-top fixed"
  .absolute class="blue margin-left-15 logo-div" 
    - "Photo Album".each_char do |l|
        p.logo = l
  .pull-right
    = link_to "Edit user", edit_user_registration_path, class: "logout btn btn-default"
    = link_to "Logout", destroy_user_session_path, method: :delete, class: "logout btn btn-default"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photo Album</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <% if user_signed_in? %>
      <%= render "layouts/navbar" %>
      <%= render "layouts/nav" %>
    <% end %>

      <div class="">
        <%= yield %>
      </div>
      
  </body>
</html>